# src/common/constants.py
# Zoom 관련 상수들

# 창 검색 관련
ZOOM_PARTICIPANTS_WINDOW_TITLE = "참가자"
ZOOM_WINDOW_TITLE_CONTAINS = ["참가자", "Participants"]

# 스크롤 관련
DEFAULT_SCROLL_DELAY = 0.8
MAX_SCROLL_ATTEMPTS = 60
SCROLL_PAGE_DOWN_COUNT = 2

# 대규모 참가자 처리를 위한 설정
LARGE_PARTICIPANT_THRESHOLD = 1000  # 대규모 참가자 기준
MEDIUM_PARTICIPANT_THRESHOLD = 500  # 중간 규모 참가자 기준

# 대규모 참가자용 스크롤 설정
LARGE_PARTICIPANT_SCROLL_ATTEMPTS = 500
LARGE_PARTICIPANT_SCROLL_DELAY = 2.0
LARGE_PARTICIPANT_CONSECUTIVE_LIMIT = 10

# 중간 규모 참가자용 스크롤 설정
MEDIUM_PARTICIPANT_SCROLL_ATTEMPTS = 300
MEDIUM_PARTICIPANT_SCROLL_DELAY = 1.8
MEDIUM_PARTICIPANT_CONSECUTIVE_LIMIT = 8

# 일반 참가자용 스크롤 설정
NORMAL_PARTICIPANT_SCROLL_ATTEMPTS = 50  # 대폭 감소
NORMAL_PARTICIPANT_SCROLL_DELAY = 0.8    # 대기 시간 단축
NORMAL_PARTICIPANT_CONSECUTIVE_LIMIT = 3  # 연속 체크 횟수 감소

# 대기 시간 설정
LARGE_PARTICIPANT_INITIAL_DELAY = 3.0
NORMAL_PARTICIPANT_INITIAL_DELAY = 2.0

# 진행 상황 로깅 간격 (초)
PROGRESS_LOG_INTERVAL = 10

# UI 요소 관련
PARTICIPANT_CONTROL_PATTERNS = ['list', 'item', 'participant', 'user']
SUPPORTED_CONTROL_TYPES = ['ListItem', 'List', 'Custom']

# 파일 관련
DEFAULT_OUTPUT_DIR = "output"
DEFAULT_LOG_DIR = "logs"
PARTICIPANTS_FILE_PREFIX = "zoom_participants"

# 로깅 관련
DEFAULT_LOG_LEVEL = "INFO"
LOG_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
GUI_LOG_FORMAT = '%(levelname)s: %(message)s' 